commit-msg:
  commands:
    commitlint:
      skip: [merge, rebase]
      run: pnpm dlx commitlint --edit {1}

pre-commit:
  parallel: true
  commands:
    eslint:
      glob: '*.{js,ts,json,json5,jsonc,yml,yaml,md}'
      skip: [merge, rebase]
      run: pnpm eslint {staged_files} --fix
      stage_fixed: true
